import { Lipstick } from "../../../assets/assets";
const productDetails = [
  {
    id: 1,
    name: "Moisture Matte Long Stay",
    price: 500,
    image: Lipstick,
    rating: 4,
    reviews: 36,
    imageUrl: " ",
    discount: "20% OFF",
    category: "Eyeliner",
    color: "bg-pink-700",
    dresStyle: "Casuals",
    brands: "Lakme",
    shade:"Pink",
    material:"Soft",
  },
  {
    id: 2,
    name: "Moisture Matte Long Stay",
    price: 400,
    image: Lipstick,
    rating: 3,
    reviews: 36,
    imageUrl: " ",
    category: "Lipstick",
    color: "bg-yellow-700",
    dresStyle: "Formals",
    brands: "HudaBeauty",
    shade:"Pink",
    material:"Hard",
    discount: "10% OFF"
  },
  {
    id: 3,
    name: "Moisture Matte Long Stay",
    price: 600,
    image: Lipstick,
    rating: 2,
    reviews: 36,
    imageUrl: " ",
    category: "Kajal",
    color: "bg-red-700",
    dresStyle: "Party",
    brands: "Renne",
    shade:"Rose",
    discount: "10% OFF",
    material:"Hard",
  },
  {
    id: 4,
    name: "Moisture Matte Long Stay",
    price: 500,
    image: Lipstick,
    rating: 1,
    reviews: 36,
    imageUrl: " ",
    category: "Mascara",
    color: "bg-pink-500",
    dresStyle: "Gym",
    brands: "Nars",
    shade:"Pink",
    discount: "20% OFF",
    material:"Soft",
  },
  {
    id: 5,
    name: "Moisture Matte Long Stay",
    price: 500,
    image: Lipstick,
    rating: 2,
    reviews: 36,
    imageUrl: " ",
    category: "Foundation",
    color: "bg-blue-500",
    dresStyle: "Casuals",
    brands: "Ravlon",
    shade:"Dark Pink",
    discount: "20% OFF",
    material:"Soft",
  },
  {
    id: 6,
    name: "Moisture Matte Long Stay",
    price: 500,
    image: Lipstick,
    rating: 3,
    reviews: 36,
    imageUrl: " ",
    category: "Eyeliner",
    color: "bg-red-500",
    dresStyle: "Formals",
    brands: "Sugar",
    shade:"Rose",
    discount: "20% OFF",
    material:"Soft",
  },
  {
    id: 7,
    name: "Moisture Matte Long Stay",
    price: 400,
    image: Lipstick,
    rating: 5,
    reviews: 36,
    imageUrl: " ",
    category: "Mascara",
    color: "bg-green-500",
    dresStyle: "Gym",
    brands: "MAC",
    shade:"Rose",
    discount: "10% OFF",
    material:"Soft",

  },
  {
    id: 8,
    name: "Moisture Matte Long Stay",
    price: 400,
    image: Lipstick,
    rating: 4,
    reviews: 36,
    imageUrl: " ",
    category: "Lipstick",
    color: "bg-yellow-500",
    dresStyle: "Party",
    brands: "AVEDA",
    shade:"Pink",
    discount: "10% OFF",
    material:"Soft",
  },
  {
    id: 9,
    name: "Moisture Matte Long Stay",
    price: 400,
    image: Lipstick,
    rating: 4,
    reviews: 36,
    imageUrl: " ",
    category: "Eyeliner",
    color: "bg-pink-400",
    shade:"Pink",
    dresStyle: "Gym",
    brands: "Lakme",
    discount: "20% OFF",
    material:"Hard",
  },
  {
    id: 10,
    name: "Moisture Matte Long Stay",
    price: 400,
    image: Lipstick,
    rating: 4,
    reviews: 36,
    imageUrl: " ",
    category: "Eyeliner",
    color: "bg-pink-400",
    shade:"Pink",
    dresStyle: "Gym",
    brands: "Lakme",
    discount: "20% OFF",
    material:"Hard",
  },
  {
    id: 11,
    name: "Moisture Matte Long Stay",
    price: 400,
    image: Lipstick,
    rating: 4,
    reviews: 36,
    imageUrl: " ",
    category: "Eyeliner",
    color: "bg-pink-400",
    shade:"Pink",
    dresStyle: "Gym",
    brands: "Lakme",
    discount: "20% OFF",
    material:"Hard",
  },
  {
    id: 12,
    name: "Moisture Matte Long Stay",
    price: 400,
    image: Lipstick,
    rating: 4,
    reviews: 36,
    imageUrl: " ",
    category: "Eyeliner",
    color: "bg-pink-400",
    shade:"Pink",
    dresStyle: "Gym",
    brands: "Lakme",
    discount: "20% OFF",
    material:"Hard",
  },
];

export default productDetails;